### ISSUE TITLE
fix/design-fix

### ISSUE THREAD

**Issue by Gunbam27** [Team-FloWee/kovel-app#209]
## 세부 사항

- [x] 홈 Appbar height가 너무 큼 => 기본앱바 사용
- [x] Scaffold body 색이 흰색이 아님
- [x] 홈화면 안녕하세요, 부분 영문 추가해야함
- [x] 홈화면 borderRadius 양쪽 반영하기
- [x] 디테일 페이지 하트가 안보임

**Comment by jungeun272** [comment]
우리 홈화면에서 기본앱바를 아예 지우는게 좋을 거 같아요~
